version: '3.4'

services:
  webixkanban:
    image: ${DOCKER_REGISTRY-}webixkanban
    build:
      context: .
      dockerfile: WebixKanban/Dockerfile
  sqlkanban:
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: "SqlDevOps2017"
      ACCEPT_EULA: "Y"